import { Checkout, HistoryEntry, InventoryNotification, InventoryState, Item, User } from './types';

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
const daysFromNow = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Sarah Johnson',
    email: 'sarah.j@school.edu',
    role: 'equipment-manager',
    roles: ['equipment-manager'],
    permissions: ['checkout', 'bulk-checkout', 'damage-log', 'admin'],
    groups: ['Athletics', 'IT Desk'],
    active: true,
    restricted: false,
    repeatOffender: false,
  },
  {
    id: 'u2',
    name: 'Mike Chen',
    email: 'mike.c@school.edu',
    role: 'coach',
    roles: ['coach'],
    permissions: ['checkout', 'bulk-checkout', 'damage-log'],
    groups: ['Athletics'],
    active: true,
    restricted: false,
    repeatOffender: false,
  },
  {
    id: 'u3',
    name: 'Emma Davis',
    email: 'emma.d@school.edu',
    role: 'student',
    roles: ['student'],
    permissions: ['checkout'],
    groups: ['Media Club'],
    active: true,
    restricted: false,
    repeatOffender: false,
  },
  {
    id: 'u4',
    name: 'James Wilson',
    email: 'james.w@school.edu',
    role: 'student',
    roles: ['student', 'coach'],
    permissions: ['checkout'],
    groups: ['Basketball', 'Student Staff'],
    active: true,
    restricted: false,
    repeatOffender: true,
  },
  {
    id: 'u5',
    name: 'Lisa Brown',
    email: 'lisa.b@school.edu',
    role: 'student',
    roles: ['student'],
    permissions: [],
    groups: ['Photography'],
    active: true,
    restricted: true,
    repeatOffender: true,
  },
  {
    id: 'u6',
    name: 'Tom Martinez',
    email: 'tom.m@school.edu',
    role: 'student',
    roles: ['student'],
    permissions: ['checkout'],
    groups: ['Robotics'],
    active: false,
    restricted: false,
    repeatOffender: false,
  },
];

export const mockItems: Item[] = [
  {
    id: 'i1',
    barcode: 'EQ001234',
    name: 'MacBook Pro 14" M3',
    category: 'Electronics',
    status: 'available',
    condition: 'excellent',
    kind: 'single',
    photoUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 1,
    availableQuantity: 1,
    checkedOutQuantity: 0,
    damagedQuantity: 0,
    lostQuantity: 0,
    damageLevel: 'none',
    restockFlag: false,
    createdAt: daysAgo(44),
  },
  {
    id: 'i2',
    barcode: 'EQ001235',
    name: 'Canon EOS R6 Camera',
    category: 'Electronics',
    status: 'available',
    condition: 'good',
    kind: 'single',
    photoUrl: 'https://images.unsplash.com/photo-1500634245200-e5245c7574ef?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 1,
    availableQuantity: 1,
    checkedOutQuantity: 0,
    damagedQuantity: 0,
    lostQuantity: 0,
    damageLevel: 'none',
    restockFlag: false,
    createdAt: daysAgo(30),
  },
  {
    id: 'i3',
    barcode: 'EQ001236',
    name: 'Badminton Racquets',
    category: 'Sports Equipment',
    status: 'checked-out',
    condition: 'good',
    kind: 'bulk',
    photoUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 24,
    availableQuantity: 18,
    checkedOutQuantity: 6,
    damagedQuantity: 0,
    lostQuantity: 0,
    damageLevel: 'none',
    restockFlag: false,
    currentHolder: 'u3',
    checkoutDate: daysAgo(1),
    dueDate: daysFromNow(2),
    createdAt: daysAgo(80),
  },
  {
    id: 'i4',
    barcode: 'EQ001237',
    name: 'Projector - Epson 2250U',
    category: 'Electronics',
    status: 'overdue',
    condition: 'fair',
    kind: 'single',
    photoUrl: 'https://images.unsplash.com/photo-1612296727716-d6c69d2a2c72?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 1,
    availableQuantity: 0,
    checkedOutQuantity: 1,
    damagedQuantity: 0,
    lostQuantity: 0,
    damageLevel: 'none',
    restockFlag: false,
    currentHolder: 'u4',
    checkoutDate: daysAgo(7),
    dueDate: daysAgo(2),
    lastSeenWith: 'u4',
    createdAt: daysAgo(61),
  },
  {
    id: 'i5',
    barcode: 'EQ001238',
    name: 'Yoga Mats',
    category: 'Fitness',
    status: 'available',
    condition: 'excellent',
    kind: 'bulk',
    photoUrl: 'https://images.unsplash.com/photo-1591291621164-2c6367723315?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 40,
    availableQuantity: 40,
    checkedOutQuantity: 0,
    damagedQuantity: 0,
    lostQuantity: 0,
    damageLevel: 'none',
    restockFlag: false,
    createdAt: daysAgo(45),
  },
  {
    id: 'i6',
    barcode: 'EQ001239',
    name: 'iPad Pro 12.9" 2024',
    category: 'Electronics',
    status: 'checked-out',
    condition: 'excellent',
    kind: 'single',
    photoUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 1,
    availableQuantity: 0,
    checkedOutQuantity: 1,
    damagedQuantity: 0,
    lostQuantity: 0,
    damageLevel: 'none',
    restockFlag: false,
    currentHolder: 'u1',
    checkoutDate: daysAgo(1),
    dueDate: daysFromNow(1),
    createdAt: daysAgo(14),
  },
  {
    id: 'i7',
    barcode: 'EQ001240',
    name: 'DSLR Tripod - Manfrotto',
    category: 'Photography',
    status: 'damaged',
    condition: 'damaged',
    kind: 'single',
    photoUrl: 'https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 1,
    availableQuantity: 0,
    checkedOutQuantity: 0,
    damagedQuantity: 1,
    lostQuantity: 0,
    damageLevel: 'major',
    restockFlag: true,
    lastSeenWith: 'u5',
    createdAt: daysAgo(120),
  },
  {
    id: 'i8',
    barcode: 'EQ001241',
    name: 'Wireless Microphone Sets',
    category: 'Audio',
    status: 'available',
    condition: 'good',
    kind: 'bulk',
    photoUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 8,
    availableQuantity: 5,
    checkedOutQuantity: 2,
    damagedQuantity: 1,
    lostQuantity: 0,
    damageLevel: 'minor',
    restockFlag: false,
    currentHolder: 'u2',
    checkoutDate: daysAgo(1),
    dueDate: daysFromNow(2),
    createdAt: daysAgo(22),
  },
  {
    id: 'i9',
    barcode: 'EQ001242',
    name: 'Kettlebells 15lb',
    category: 'Weights',
    status: 'overdue',
    condition: 'excellent',
    kind: 'bulk',
    photoUrl: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 12,
    availableQuantity: 8,
    checkedOutQuantity: 4,
    damagedQuantity: 0,
    lostQuantity: 0,
    damageLevel: 'none',
    restockFlag: false,
    currentHolder: 'u4',
    checkoutDate: daysAgo(9),
    dueDate: daysAgo(4),
    lastSeenWith: 'u4',
    createdAt: daysAgo(96),
  },
  {
    id: 'i10',
    barcode: 'EQ001243',
    name: 'USB-C Cable Bin',
    category: 'IT Accessories',
    status: 'available',
    condition: 'fair',
    kind: 'bulk',
    photoUrl: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=600&q=80',
    totalQuantity: 60,
    availableQuantity: 11,
    checkedOutQuantity: 32,
    damagedQuantity: 7,
    lostQuantity: 10,
    damageLevel: 'minor',
    restockFlag: true,
    createdAt: daysAgo(160),
  },
];

export const mockCheckouts: Checkout[] = [
  { id: 'c1', itemId: 'i3', userId: 'u3', quantity: 6, checkoutDate: daysAgo(1), dueDate: daysFromNow(2), status: 'active' },
  { id: 'c2', itemId: 'i4', userId: 'u4', quantity: 1, checkoutDate: daysAgo(7), dueDate: daysAgo(2), status: 'overdue' },
  { id: 'c3', itemId: 'i6', userId: 'u1', quantity: 1, checkoutDate: daysAgo(1), dueDate: daysFromNow(1), status: 'active' },
  { id: 'c4', itemId: 'i8', userId: 'u2', quantity: 2, checkoutDate: daysAgo(1), dueDate: daysFromNow(2), status: 'active' },
  { id: 'c5', itemId: 'i9', userId: 'u4', quantity: 4, checkoutDate: daysAgo(9), dueDate: daysAgo(4), status: 'overdue' },
];

export const mockHistory: HistoryEntry[] = [
  { id: 'h1', itemId: 'i3', userId: 'u3', action: 'checkout', timestamp: daysAgo(1), condition: 'good', quantity: 6 },
  { id: 'h2', itemId: 'i4', userId: 'u4', action: 'checkout', timestamp: daysAgo(7), condition: 'fair', quantity: 1 },
  { id: 'h3', itemId: 'i7', userId: 'u5', action: 'damage-report', timestamp: daysAgo(5), condition: 'damaged', damageLevel: 'major', quantity: 1, notes: 'Center column no longer locks.' },
  { id: 'h4', itemId: 'i6', userId: 'u1', action: 'checkout', timestamp: daysAgo(1), condition: 'excellent', quantity: 1 },
  { id: 'h5', itemId: 'i9', userId: 'u4', action: 'checkout', timestamp: daysAgo(9), condition: 'excellent', quantity: 4 },
  { id: 'h6', itemId: 'i10', action: 'lost-report', timestamp: daysAgo(13), quantity: 10, notes: 'Annual cable audit variance.' },
];

export const mockNotifications: InventoryNotification[] = [
  {
    id: 'n1',
    itemId: 'i4',
    userId: 'u4',
    channel: 'email',
    trigger: 'overdue',
    priority: 'high',
    message: 'Projector - Epson 2250U is 2 days overdue. Nudge sent to James Wilson.',
    createdAt: daysAgo(1),
    sent: true,
    read: false,
  },
  {
    id: 'n2',
    itemId: 'i7',
    userId: 'u5',
    channel: 'email',
    trigger: 'damaged',
    priority: 'critical',
    message: 'DSLR Tripod - Manfrotto marked major damage and needs admin review.',
    createdAt: daysAgo(5),
    sent: true,
    read: false,
  },
];

export const initialInventoryState: InventoryState = {
  items: mockItems,
  users: mockUsers,
  checkouts: mockCheckouts,
  history: mockHistory,
  notifications: mockNotifications,
};
